---
stories:
  "/Users/macbookpro/hero/tasks/src/144642129900.md": !ruby/object:CliTasks::Note
    data: 'maintain an archive of all the cli tools i''ve made, records of everytime
      i''ve ran it, when and with what args, periodically remind myself of what tools
      are available and how long it has been since last using it #bash/todo #hero/todo
      #tools/util-archive'
    file: "/Users/macbookpro/hero/tasks/src/144642129900.md"
    lines:
    - 'maintain an archive of all the cli tools i''ve made, records of everytime i''ve
      ran it, when and with what args, periodically remind myself of what tools are
      available and how long it has been since last using it #bash/todo #hero/todo
      #tools/util-archive'
    tags:
    - bash/todo
    - hero/todo
    - tools/util-archive
    metadata: {}
    body:
    - 'maintain an archive of all the cli tools i''ve made, records of everytime i''ve
      ran it, when and with what args, periodically remind myself of what tools are
      available and how long it has been since last using it #bash/todo #hero/todo
      #tools/util-archive'
    name: 'maintain an archive of all the cli tools i''ve made, records of everytime
      i''ve ran it, when and with what args, periodically remind myself of what tools
      are available and how long it has been since last using it #bash/todo #hero/todo
      #tools/util-archive'
  "/Users/macbookpro/hero/tasks/src/144648668400.md": !ruby/object:CliTasks::Note
    data: |+
      reorganize either bin/H or its subcmds to be more project-centric; either that, or make a binstub for each 'project' (see examples below)

      so here is a set of actions, basically a use case
      demonstrating how multiple tools will work together to give
      the developer a simple user experience:

      ```
      # hero project add [project-name] [project-path]

      $> hero project add hiro ~/repos/hero-project

        Adding a new project to $HOME/hero/projects.yml...
          name: 'hiro'
          path: '/Users/unixsuperhero/repos/hero-project'

          Generating binstub...
            Saving to =>
              $HOME/hero/bin/hiro
              $HOME/hero/projects/bin/hiro
          done
        done

      $> hiro task save 'release v0.0.1 of the hero project'
      $> hiro tmux

        Command: tmux new -s hiro -c $HOME/repos/hero-project

      $>
      ```

      #hero/h #hero/todo #todo/hero

    file: "/Users/macbookpro/hero/tasks/src/144648668400.md"
    lines:
    - reorganize either bin/H or its subcmds to be more project-centric; either that,
      or make a binstub for each 'project' (see examples below)
    - ''
    - so here is a set of actions, basically a use case
    - demonstrating how multiple tools will work together to give
    - 'the developer a simple user experience:'
    - ''
    - "```"
    - "# hero project add [project-name] [project-path]"
    - ''
    - "$> hero project add hiro ~/repos/hero-project"
    - ''
    - "  Adding a new project to $HOME/hero/projects.yml..."
    - "    name: 'hiro'"
    - "    path: '/Users/unixsuperhero/repos/hero-project'"
    - ''
    - "    Generating binstub..."
    - "      Saving to =>"
    - "        $HOME/hero/bin/hiro"
    - "        $HOME/hero/projects/bin/hiro"
    - "    done"
    - "  done"
    - ''
    - "$> hiro task save 'release v0.0.1 of the hero project'"
    - "$> hiro tmux"
    - ''
    - "  Command: tmux new -s hiro -c $HOME/repos/hero-project"
    - ''
    - "$>"
    - "```"
    - ''
    - "#hero/h #hero/todo #todo/hero"
    - ''
    tags:
    - hero/h
    - hero/todo
    - todo/hero
    metadata: {}
    body:
    - reorganize either bin/H or its subcmds to be more project-centric; either that,
      or make a binstub for each 'project' (see examples below)
    - ''
    - so here is a set of actions, basically a use case
    - demonstrating how multiple tools will work together to give
    - 'the developer a simple user experience:'
    - ''
    - "```"
    - "# hero project add [project-name] [project-path]"
    - ''
    - "$> hero project add hiro ~/repos/hero-project"
    - ''
    - "  Adding a new project to $HOME/hero/projects.yml..."
    - "    name: 'hiro'"
    - "    path: '/Users/unixsuperhero/repos/hero-project'"
    - ''
    - "    Generating binstub..."
    - "      Saving to =>"
    - "        $HOME/hero/bin/hiro"
    - "        $HOME/hero/projects/bin/hiro"
    - "    done"
    - "  done"
    - ''
    - "$> hiro task save 'release v0.0.1 of the hero project'"
    - "$> hiro tmux"
    - ''
    - "  Command: tmux new -s hiro -c $HOME/repos/hero-project"
    - ''
    - "$>"
    - "```"
    - ''
    - "#hero/h #hero/todo #todo/hero"
    - ''
    name: reorganize either bin/H or its subcmds to be more project-centric; either
      that, or make a binstub for each 'project' (see examples below)
  "/Users/macbookpro/hero/tasks/src/144649033800.md": !ruby/object:CliTasks::Note
    data: 'create "project" subcommand which will add name/path to projects.yml and
      generate a binstub similar to note/task or the heroku binstubs #hero/projects
      #hero/subcmd #projects #todo #subcmd/create'
    file: "/Users/macbookpro/hero/tasks/src/144649033800.md"
    lines:
    - 'create "project" subcommand which will add name/path to projects.yml and generate
      a binstub similar to note/task or the heroku binstubs #hero/projects #hero/subcmd
      #projects #todo #subcmd/create'
    tags:
    - hero/projects
    - hero/subcmd
    - projects
    - subcmd/create
    - todo
    metadata: {}
    body:
    - 'create "project" subcommand which will add name/path to projects.yml and generate
      a binstub similar to note/task or the heroku binstubs #hero/projects #hero/subcmd
      #projects #todo #subcmd/create'
    name: 'create "project" subcommand which will add name/path to projects.yml and
      generate a binstub similar to note/task or the heroku binstubs #hero/projects
      #hero/subcmd #projects #todo #subcmd/create'
  "/Users/macbookpro/hero/tasks/src/144684769000.md": !ruby/object:CliTasks::Note
    data: "#todo go thru zsh history to find frequently used git/shell recipes"
    file: "/Users/macbookpro/hero/tasks/src/144684769000.md"
    lines:
    - "#todo go thru zsh history to find frequently used git/shell recipes"
    tags:
    - todo
    metadata: {}
    body:
    - "#todo go thru zsh history to find frequently used git/shell recipes"
    name: "#todo go thru zsh history to find frequently used git/shell recipes"
  "/Users/macbookpro/hero/tasks/src/144688744200.md": !ruby/object:CliTasks::Note
    data: |
      write an article expaining all the reasons why i write my POROs the way i do

      and the 3 ways to return the instance from a class method

      1. tempvar = new(); tempvar.run; tempvar
      2. new().tap(&:run)
      3. new().run; # and `\#run` will return `self`

      #hero/training #todo/training
    file: "/Users/macbookpro/hero/tasks/src/144688744200.md"
    lines:
    - write an article expaining all the reasons why i write my POROs the way i do
    - ''
    - and the 3 ways to return the instance from a class method
    - ''
    - 1. tempvar = new(); tempvar.run; tempvar
    - 2. new().tap(&:run)
    - '3. new().run; # and `\#run` will return `self`'
    - ''
    - "#hero/training #todo/training"
    tags:
    - hero/training
    - todo/training
    metadata: {}
    body:
    - write an article expaining all the reasons why i write my POROs the way i do
    - ''
    - and the 3 ways to return the instance from a class method
    - ''
    - 1. tempvar = new(); tempvar.run; tempvar
    - 2. new().tap(&:run)
    - '3. new().run; # and `\#run` will return `self`'
    - ''
    - "#hero/training #todo/training"
    name: write an article expaining all the reasons why i write my POROs the way
      i do
  "/Users/macbookpro/hero/tasks/src/144688744201.md": !ruby/object:CliTasks::Note
    data: |
      prepare an exercise demonstrating how to write tests for a 300 line legacy
      method

      #todo/training
    file: "/Users/macbookpro/hero/tasks/src/144688744201.md"
    lines:
    - prepare an exercise demonstrating how to write tests for a 300 line legacy
    - method
    - ''
    - "#todo/training"
    tags:
    - todo/training
    metadata: {}
    body:
    - prepare an exercise demonstrating how to write tests for a 300 line legacy
    - method
    - ''
    - "#todo/training"
    name: prepare an exercise demonstrating how to write tests for a 300 line legacy
  "/Users/macbookpro/hero/tasks/src/144688744202.md": !ruby/object:CliTasks::Note
    data: |
      prepare a lesson about writing pseudocode and making real code out of it

      #todo/training
    file: "/Users/macbookpro/hero/tasks/src/144688744202.md"
    lines:
    - prepare a lesson about writing pseudocode and making real code out of it
    - ''
    - "#todo/training"
    tags:
    - todo/training
    metadata: {}
    body:
    - prepare a lesson about writing pseudocode and making real code out of it
    - ''
    - "#todo/training"
    name: prepare a lesson about writing pseudocode and making real code out of it
  "/Users/macbookpro/hero/tasks/src/144688952700.md": !ruby/object:CliTasks::Note
    data: |
      make a new h command that can list all subcmds and extensions because it loads
      them instead of firing a new process

      there are so many benefits to this.

      * it is the easiest way to pass data piped in from one class to another

      #hero/todo #todo/hero
    file: "/Users/macbookpro/hero/tasks/src/144688952700.md"
    lines:
    - make a new h command that can list all subcmds and extensions because it loads
    - them instead of firing a new process
    - ''
    - there are so many benefits to this.
    - ''
    - "* it is the easiest way to pass data piped in from one class to another"
    - ''
    - "#hero/todo #todo/hero"
    tags:
    - hero/todo
    - todo/hero
    metadata: {}
    body:
    - make a new h command that can list all subcmds and extensions because it loads
    - them instead of firing a new process
    - ''
    - there are so many benefits to this.
    - ''
    - "* it is the easiest way to pass data piped in from one class to another"
    - ''
    - "#hero/todo #todo/hero"
    name: make a new h command that can list all subcmds and extensions because it
      loads
  "/Users/macbookpro/hero/tasks/src/144689197900.md": !ruby/object:CliTasks::Note
    data: |
      write a subcommand that will track when an alias or function is created, which
      one it is, and in which file.  the same cmd could be used to edit it later on

      #hero/todo #todo/hero #bash/todo
    file: "/Users/macbookpro/hero/tasks/src/144689197900.md"
    lines:
    - write a subcommand that will track when an alias or function is created, which
    - one it is, and in which file.  the same cmd could be used to edit it later on
    - ''
    - "#hero/todo #todo/hero #bash/todo"
    tags:
    - bash/todo
    - hero/todo
    - todo/hero
    metadata: {}
    body:
    - write a subcommand that will track when an alias or function is created, which
    - one it is, and in which file.  the same cmd could be used to edit it later on
    - ''
    - "#hero/todo #todo/hero #bash/todo"
    name: write a subcommand that will track when an alias or function is created,
      which
  "/Users/macbookpro/hero/tasks/src/144689283000.md": !ruby/object:CliTasks::Note
    data: 'make a directory for reusable ruby libs or shell scripts (normally start
      as experiments) #todo/hero #hero/todo'
    file: "/Users/macbookpro/hero/tasks/src/144689283000.md"
    lines:
    - 'make a directory for reusable ruby libs or shell scripts (normally start as
      experiments) #todo/hero #hero/todo'
    tags:
    - hero/todo
    - todo/hero
    metadata: {}
    body:
    - 'make a directory for reusable ruby libs or shell scripts (normally start as
      experiments) #todo/hero #hero/todo'
    name: 'make a directory for reusable ruby libs or shell scripts (normally start
      as experiments) #todo/hero #hero/todo'
  "/Users/macbookpro/hero/tasks/src/144692264900.md": !ruby/object:CliTasks::Note
    data: create a project all subcommand for running a command on all the projects
    file: "/Users/macbookpro/hero/tasks/src/144692264900.md"
    lines:
    - create a project all subcommand for running a command on all the projects
    tags: []
    metadata: {}
    body:
    - create a project all subcommand for running a command on all the projects
    name: create a project all subcommand for running a command on all the projects
  "/Users/macbookpro/hero/tasks/src/144760651000.md": !ruby/object:CliTasks::Note
    data: 'add heavier subcommands to h-project like task that takes its own subcommands,
      load the file somehow and call the class directly #hero/projects #hero/todo
      #todo/hero'
    file: "/Users/macbookpro/hero/tasks/src/144760651000.md"
    lines:
    - 'add heavier subcommands to h-project like task that takes its own subcommands,
      load the file somehow and call the class directly #hero/projects #hero/todo
      #todo/hero'
    tags:
    - hero/projects
    - hero/todo
    - todo/hero
    metadata: {}
    body:
    - 'add heavier subcommands to h-project like task that takes its own subcommands,
      load the file somehow and call the class directly #hero/projects #hero/todo
      #todo/hero'
    name: 'add heavier subcommands to h-project like task that takes its own subcommands,
      load the file somehow and call the class directly #hero/projects #hero/todo
      #todo/hero'
tags:
  bash/todo: []
  hero/todo: []
  tools/util-archive: []
  hero/h: []
  todo/hero: []
  hero/projects: []
  hero/subcmd: []
  projects: []
  subcmd/create: []
  todo: []
  hero/training: []
  todo/training: []
